from QRCORE import single

if __name__ == "__main__":
    single("../static/picture/clockin.png",
           'http://ehall.cqupt.edu.cn/publicapp/sys/cyxsjkdkmobile/*default/index.html')
    single('../static/picture/goout.png', 'http://ehall.cqupt.edu.cn/publicappnew/sys/crxglxtnew/mobile/index.html')
    single('../static/picture/acid.png', 'http://ehall.cqupt.edu.cn/publicapp/sys/cyhscj/mobile/index.html')
    single('../static/picture/lecture.png', 'http://ehall.cqupt.edu.cn/publicapp/sys/oaxsjzcxmobile/index.html')
    single('../static/picture/oa.png', 'https://mzhxg.cqupt.edu.cn/')
    single('../static/picture/dormi.png', 'http://ihome.cqupt.edu.cn/kiosk-mobile/shiro-cas')
    single('../static/picture/face.png', 'https://face.cqupt.edu.cn/')
    single('../static/picture/windowedcollege.png', 'https://gis.cqupt.edu.cn/cmipsh5/')
    single('../static/picture/tax.png', 'https://jzsf.cqupt.edu.cn/')
    single('../static/picture/dialbook.png', 'http://ehall.cqupt.edu.cn/publicapp/sys/cyxyhy/mobile/index.html')
    single('../static/picture/library.png', 'http://202.202.43.73:8000')
    single('../static/picture/ESP.png', 'http://olap.epsnet.com.cn')
    single('../static/picture/chaoxing.png', 'https://www.chaoxing.com/')
    single('../static/picture/rdfybk.png', 'http://www.rdfybk.com/')
    single('../static/picture/login.png', 'https://ids.cqupt.edu.cn/authserver/login')
    single('../static/picture/wecqupt.png', 'https://mp.weixin.qq.com/a/9yp_ZtPEZY8brZcF93-l?v=2')
    single('../static/picture/wecquptbk.png', 'https://mp.weixin.qq.com/a/9yp_ZtPEZY8brZcF93-l?v=2')
    single('../static/picture/welcome2022.png', 'http://szyx.cqupt.edu.cn/szyx2022/login.php')
    single('../static/picture/epidemic@disabled.png', 'https://mp.weixin.qq.com/a/9yp_ZtPEZY8brZcF93-l?v=2')
    single('../static/picture/kb@disabled.png', 'https://mp.weixin.qq.com/a/9yp_ZtPEZY8brZcF93-l?v=2')
    single('../static/picture/ks@disabled.png', 'https://mp.weixin.qq.com/a/9yp_ZtPEZY8brZcF93-l?v=2')
    single('../static/picture/kjs@disabled.png', 'https://mp.weixin.qq.com/a/9yp_ZtPEZY8brZcF93-l?v=2')
    single('../static/picture/xl@disabled.png', 'https://mp.weixin.qq.com/a/9yp_ZtPEZY8brZcF93-l?v=2')
    single('../static/picture/tsgzw@disabled.png', 'https://mp.weixin.qq.com/a/9yp_ZtPEZY8brZcF93-l?v=2')
    single('../static/picture/ts@disabled.png', 'https://mp.weixin.qq.com/a/9yp_ZtPEZY8brZcF93-l?v=2')
    single('../static/picture/jy@disabled.png', 'https://mp.weixin.qq.com/a/9yp_ZtPEZY8brZcF93-l?v=2')
    # single('../static/picture/xskjjs@disabled.png', 'https://mp.weixin.qq.com/a/9yp_ZtPEZY8brZcF93-l?v=2')
    single('../static/picture/swzl@disabled.png', 'https://mp.weixin.qq.com/a/9yp_ZtPEZY8brZcF93-l?v=2')
    single('../static/picture/bx@disabled.png', 'https://mp.weixin.qq.com/a/9yp_ZtPEZY8brZcF93-l?v=2')
    single('../static/picture/fxxcb@disabled.png', 'https://mp.weixin.qq.com/a/9yp_ZtPEZY8brZcF93-l?v=2')
    single('../static/picture/sdf@disabled.png', 'https://mp.weixin.qq.com/a/9yp_ZtPEZY8brZcF93-l?v=2')
    single("../static/picture/xxdk.png", "http://szyx.cqupt.edu.cn/xxdk")
    single('../static/picture/pe_old.png', 'http://202.202.43.198/mobile/index')
    single('../static/picture/pe_new.png', 'http://172.20.2.228/portal')
    single('../static/picture/sxhqd.png', 'http://ehall.cqupt.edu.cn/publicapp/sys/cquptsmqd/mobile/index.html')
    single('../static/picture/xstbfw.png', 'http://studata.cqupt.edu.cn/platform/index')
    single('../static/picture/myyear.png', 'http://year.cqupt.edu.cn/MyYear')
    single('../static/picture/tc.png', 'http://mobile.tc.cqupt.edu.cn/')
    single('../static/picture/xtbg.png', 'http://studata.cqupt.edu.cn/platform/index')
